### ISSUE TITLE
[ERROR] in the msftmrho output 

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#281] opened 2021-05-26 09:46 UTC
**Describe the error**
 The cmorized variable msftmrho is looking identical to the raw model output for the atlantic_arctic_ocean sector (basin), but zero for all other sectors (global_ocean, indian_pacific_ocean,atlantic_arctic_extended_ocean) regardless of experiment.

E.g.
/projects/NS9034K/CMIP6//CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Omon/msftmrho/grz/latest/msftmrho_Omon_NorESM2-LM_piControl_r1i1p1f1_grz_160001-160912.nc

The same problem seems to be the case with msftmrhompa as well

**Comment by YanchunHe** [comment] 2021-07-29 08:24
This is found to be caused by a long-existing undiscovered bug, in which the dimension size of this variable in the vertical direction is not set (so with wrong dimension size).

This will be fixed in the next update.

**Comment by YanchunHe** [comment] 2021-08-11 06:44
@monsieuralok Please report an erratum to this issue for all published `msftmrho`.

**Comment by monsieuralok** [comment] 2021-08-13 08:58
@YanchunHe what should be report ? That all datasets with variable msftmrho is wrong and should not be used? There has been something wrong with dimension size. 

Should be not retract those? Are we planning to republish those? or there is any fix so people can use it? Also should be report also for msftmrhompa?

**Comment by monsieuralok** [comment] 2021-08-13 09:15
@YanchunHe opend errata issue : https://errata.es-doc.org/static/view.html?uid=f05051d2-99ad-402c-834c-d0acc8fdf482 as NorESM1-F does not have this data.

**Comment by YanchunHe** [comment] 2021-08-13 13:55
> @YanchunHe what should be report ? That all datasets with variable msftmrho is wrong and should not be used? There has been something wrong with dimension size.
> 
It is correct for the first dimension of `msftmrho` (atlantic-arctic section) but not for other sections. So the first section is usable.

And I don't plan to recmorized and republish them, so don't need to retract now. If we will do some additional cmorization for one experiments, this will be updated.

> Should be not retract those? Are we planning to republish those? or there is any fix so people can use it? Also should be report also for msftmrhompa?

looks like `msftmrhompa` is also wrong. I will check it.

**Comment by YanchunHe** [comment] 2021-08-17 13:07
I checked `msftmrhompa` is also wrong. But also be fixed in the future published datasets. 

Please include `msftmzmpa` in the erratum. Thanks!

@monsieuralok

**Comment by monsieuralok** [comment] 2021-08-23 12:57
@YanchunHe In Errata  issue I will write following: 

Datasets with variables  msftmrhompa, msftmzmpa and msftmrho are having errors and are usable except for first section (atlantic-arctic section) but not for other sections. So the first section is usable. And we don't plan to publish corrected version of these datasets. But, in future if we republish these data then, these will be publish after correction.

**Comment by monsieuralok** [comment] 2021-08-24 08:32
@YanchunHe opened errata issue : https://errata.es-doc.org/static/view.html?uid=3ba3def8-1fcf-c7ce-b701-972cbcbe4e1c

**Closed** 2021-08-24 09:01 UTC
Labels: error, Erratum
