### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM - historical

### ISSUE THREAD

**Issue by matsbn** [NorESMhub/noresm2cmor#143] opened 2019-11-21 14:24 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases
/projects/NS9560K/FRAM/noresm/cases

**experiment_id**
historical

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NHISTfrc2_f09_tn14_20191001, 1850-1949
NHISTfrc2_f09_tn14_20191025, 1950-2014

### Optional information

**parent_experiment_id**
piControl-spinup

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0001-01-01'

**branch_method**
'Hybrid-restart from year 1200-01-01 of piControl-spinup'

**other information**
The case NHISTfrc2_f09_tn14_20191001 is under /projects/NS9560K/noresm/cases, while case NHISTfrc2_f09_tn14_20191025 is under /projects/NS9560K/FRAM/noresm/cases.

**Comment by oyvindseland** [comment] 2019-12-03 07:17
Hi 
If there are any way to give this task a priority it would be nice in particular for the last period. Some of the analysis for the NorESM2  coupled simulations use cmorized data.

**Comment by YanchunHe** [comment] 2019-12-10 01:55
Years (from the first to the last) needs to rsync to NIRD: /projects/NS9034K/noresm/cases/

2010	2014

**Comment by jgriesfeller** [comment] 2019-12-11 10:02
I started working on this, but just selecting the files to be transferred takes very a very long time :-(

**Comment by jgriesfeller** [comment] 2019-12-11 10:15
the download to /tos-project1/NS9034K/noresm/cases/NHISTfrc2_f09_tn14_20191025/ has been started. ~2500 files

**Comment by jgriesfeller** [comment] 2019-12-11 12:03
The first try stopped after 30 files. :-(

**Comment by jgriesfeller** [comment] 2019-12-11 13:28
second try stopped after a similar number of files on login3. This time the 2 other transfer jobs on login1 died as well. Not good

**Comment by jgriesfeller** [comment] 2019-12-11 13:54
Tried the same thing by pushing the data from FRAM to NIRD.
Faster, and more stable so far.

**Comment by jgriesfeller** [comment] 2019-12-11 15:10
Years 2010 to 2014 have been transferred to /tos-project1/NS9034K/noresm/cases/NHISTfrc2_f09_tn14_20191025 
I hope I transferred everything needed to cmorise. 
Yanchun, can you start that, please?

**Comment by YanchunHe** [comment] 2019-12-11 15:57
It looks the last 4 years was anyhow get cmorized by  yesterday...
But it needs to do some final steps before publish.
would you execute under: $CMOR_ROOT/workflow/
```bash
./cmorPost.sh -m=NorESM2-MM -e=historical -v=v20191108 &>>logs/cmorPost.log &
```

After it finishes, check if everything is OK, and update this issue to publish the data (Alok or you will publish).

Please remember, alwalys run `checkcmorout.sh` in case namelist (/projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-MM/historical) before doing cmorPost.sh, and remove unfinished 'wrong files' (make sure no running noresm2cmor3 for this experiments).

**Comment by jgriesfeller** [comment] 2019-12-12 15:32
cmorPost.sh started

**Comment by jgriesfeller** [comment] 2019-12-13 08:46
checkcmorout.sh shows this output, but I don't know how it is supposed to look:
(base) [jang@login-nird-3 historical]$ /projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-MM/historical/checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	8
yyyy1	yyyy2	nf
1849	1859	6
1850	1859	538
1860	1869	544
1870	1879	544
1880	1889	544
1890	1899	544
1900	1909	544
1910	1919	544
1920	1929	544
1930	1939	544
1940	1949	544
1950	1959	608
1960	1969	608
1970	1979	608
1980	1989	608
1990	1999	608
2000	2009	608
2010	2014	608
Total:		9704

Can anybody tell if this is alright or not?

**Comment by matsbn** [comment] 2019-12-13 13:39
This seems consistent for the time spans (when adding 1849-1859 and 1850-1859 together) so this should go to ESGF publishing.

**Comment by YanchunHe** [comment] 2019-12-13 15:01
Hi Jan, 

The number of sha256sum entries is 9133 (/tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/.r1i1p1f1.sha256sum_v20191108),
while ./checkcmorout.sh, shows there are 9704 in total.

And both,
/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20191108.QCreport
/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20191108.links
show total number of checked/linked files are 9704
(v20191108.links have 9705 lines, but the first line is head information).

I don't know the reason, but this usually not happen, and we can usually fix this by relaunch:
```bash
/projects/NS9560K/cmor/noresm2cmor/workflow/
./cmorSha256sum.sh -m=NorESM2 -e=historical -v=v20191108 -verbose=fase &>>logs/cmorSha256sum.log &
```

**Comment by YanchunHe** [comment] 2019-12-13 15:04
cmorized

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108

(Jan, after you relaunch ./cmorSha256sum.sh, when it finishes, and see if the total entries in the .r1i1p1f1.sha256sum_v20191108 is consistent with other files, then tag a ESGF Publish label).

**Comment by YanchunHe** [comment] 2019-12-14 14:50
I have launched the script, and the sha256sum will soon finish.

Jan, you don't need to launch it.

**Comment by YanchunHe** [comment] 2019-12-14 17:02
@monsieuralok 
sha256sum will soon be ready. Please check if the total number of files in .r1i1p1f1.sha256sum_v20191108 is 9704,  it is ready to be published.

**Comment by monsieuralok** [comment] 2019-12-15 20:43
@YanchunHe  @jgriesfeller Hi, total number of files in /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/.r1i1p1f1.sha256sum_v20191108 is 5524 while in /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20191108.links 9704 entries. Please could you check it ?

**Comment by YanchunHe** [comment] 2019-12-16 09:54
I updated the sha256sum again, and now it is ready to publish.

**Comment by jgriesfeller** [comment] 2019-12-16 09:57
I just started cmorPost again to go through the whole process. I will leave it running, but otherwise I hope this does not disturb anything.
If it does we have coordinate more.

**Comment by YanchunHe** [comment] 2019-12-16 10:01
No, don't do this. cmorPost.sh will initiate and redo all the steps.
In this situation, you have only need to do cmorSha256sum.sh instead. But since I have done that. You don't need to do anything.

I Assume the cmorQC is running now by your submit. So you should kill the cmorPost.sh and let just the cmorQC finish.

Otherwise, this will interrupt the existing sha256sum file.

**Comment by jgriesfeller** [comment] 2019-12-16 10:06
I did nor know that you were working there.

But I only started cmorPost by hand.

**Comment by YanchunHe** [comment] 2019-12-16 10:09
OK, thanks, no problem, I will check this and the historical will be the first published MM experiment!

**Comment by YanchunHe** [comment] 2019-12-16 10:41
checked and ready to publish @monsieuralok 
see information above.

**Comment by monsieuralok** [comment] 2019-12-17 08:46
@matsbn @YanchunHe published

**Comment by matsbn** [comment] 2019-12-17 10:18
Great achievement from all of you!

**Comment by YanchunHe** [comment] 2019-12-29 15:25
will remove year 2010-2014 of NHISTfrc2_f09_tn14_20191025 from NS9034K now to free up space for cmorized data.

**Comment by YanchunHe** [comment] 2020-11-25 10:58
Quote @adagj 
>not big, but many of the Omon variables from NorESM2-MM, historical, ensemble member 3 the year 1860 is cmorized twice:
tos_Omon_NorESM2-MM_historical_r3i1p1f1_gn_186001-186105.nc
tos_Omon_NorESM2-MM_historical_r3i1p1f1_gn_186001-186912.nc

**Comment by YanchunHe** [comment] 2020-11-25 11:02
It is confirmed that there are 78 such incidents under:
/projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20200702

I can't recall how these were produced, but likely produced for testing and forgot purge.

I don't see if there is action needed now?
(leave a note here for tracking).

**Comment by DirkOlivie** [comment] 2020-12-16 15:14
@YanchunHe This simulation (historical, NorESM2-MM, member 1) has been rerun with extra AEROCOM diagnostics output.  Can this be cmorized, and can the results end up in r1i1p1f1?  

The results of this simulation are bit-identical to the original simulation from Mats (I have checked it), the simulation name is NHISTfrc2_f09_tn14_20200718 (one simulation covers now the whole 1850-2014 period), and the data is on /projects/NS2345K/noresm/cases.

I have filled in the standard template below, but I don't know what is the best way to proceed and whether this request might cause any complications.

### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases

**experiment_id**
historical

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NHISTfrc2_f09_tn14_20200718, 1850-2014

### Optional information

**parent_experiment_id**
piControl-spinup

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0001-01-01'

**branch_method**
'Hybrid-restart from year 1200-01-01 of piControl-spinup'

**other information**
This case NHISTfrc2_f09_tn14_20200718 (1850-2014) is bit-identical to the combination of NHISTfrc2_f09_tn14_20191001 (1850-1949) and NHISTfrc2_f09_tn14_20191025 (1950-2014), but contains extra aerosol diagnostics (AEROCOM output was activated during this new simulation).

**Comment by DirkOlivie** [comment] 2020-12-17 07:29
@YanchunHe Something I forgot to mention : this new simulation does not contain the high-frequency output.  The results from this simulations can therefore not completely replace the results from the two older ones.

**Comment by YanchunHe** [comment] 2020-12-17 07:56
> @YanchunHe Something I forgot to mention : this new simulation does not contain the high-frequency output. The results from this simulations can therefore not completely replace the results from the two older ones.

Are the new variables all belongs to the monthly aerosol table [AERMon](https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_AERmon.json) (or may with AEROday and AEROMonZ)?

If so, it would be great if you can pick out which exactly the new variables are. Or I can redo the whole cmorization, and pickup which are new (though a bit cumbersome).

**Comment by DirkOlivie** [comment] 2020-12-17 14:29
@YanchunHe Yes, it concerns only variables in AERmon.    I have listed below the variables (if there is written "(present already)", then that variable is already present.  Only the variables where nothing is added should be processed (25 in total I think).

abs550aer
airmass
bldep (present already)
ccn (present already)
cdnc (present already)
chepsoa
co2 (present already)
dms (present already)
drybc
dryoa
dryso2 (present already)
dryso4
dryss
emibc (present already)
emibvoc (present already)
emidms (present already)
emidust (present already)
emiisop (present already)
emioa (present already)
emiso2 (present already)
emiso4 (present already)
emiss (present already)
emivoc (present already)
isop (present already)
lwp (present already)
mmraerh2o
mmrbc (already present)
mmrdust (already present)
mmroa (already present)
mmrpm1
mmrpm2p5
mmrso4 (already present)
mmrsoa (already present)
mmrss (already present)
o3 (already present)
od440aer
od550aer
od550aerh2o
od550bc
od550csaer
od550dust
od550lt1aer
od550oa
od550so4
od550ss
od870aer
oh (already present)
pfull (already present)
phalf (already present)
ps (already present)
rlutaf (already present)
rlutcsaf (already present)
rsutaf (already present)
rsutcsaf (already present)
so2 (already present)
ua (already present)
va (already present)
wetbc
wetoa
wetso2 (already present)
wetso4
wetss
zg (already present)
ztp (already present)

**Comment by YanchunHe** [comment] 2020-12-17 14:34
Looks great, I will sort out! @DirkOlivie

**Comment by YanchunHe** [comment] 2020-12-21 10:02
cmorized with additional 25 AERmon fields. 

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/

**version**
- v20201001

**sha256sum**
- .r1i1p1f1.sha256sum_v20201001

**Comment by monsieuralok** [comment] 2020-12-29 09:39
@YanchunHe @DirkOlivie published

**Comment by YanchunHe** [comment] 2021-02-16 08:50
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment] 2021-03-03 11:10
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-04-14 10:55
New dataset version to fix issues #270 #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r1i1p1f1.sha256sum_v20210319

Note, `chlos` and 'siareas` are only available between 1950-2014

**Comment by monsieuralok** [comment] 2021-04-29 12:26
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-08-31 12:50
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20210818
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1

**version**
- v20210818

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1
- .r1i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment] 2021-09-01 09:51
@YanchunHe published

**Comment by oyvindseland** [comment] 2021-09-08 11:28
Asked for additional variables: 6hrPlevPt variables ps and snowmxrat  (1950-2014) and Amon snowmxrat.

**Comment by YanchunHe** [comment] 2021-09-13 10:56
cmorized `snowmxrat`  for Emon (#82) and 6hrPlevPt (#109).

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210908

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r1i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment] 2021-09-28 09:07
@YanchunHe published

**Comment by monsieuralok** [comment] 2023-01-24 11:14
@YanchunHe retracted

**Comment by YanchunHe** [comment] 2023-08-29 09:17
CMORized additional 3-hourly precipitation datasets.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r1i1p1f1.sha256sum_v20230616

**Comment by monsieuralok** [comment] 2023-08-29 12:00
@YanchunHe published

**Closed by monsieuralok** 2023-08-29 12:00 UTC
Labels: ESGF publish
