### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - ssp370

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#136] opened 2019-11-19 10:17 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/FRAM/noresm/cases

**experiment_id**
ssp370

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NSSP370frc2_f19_tn14_20191014, 2015-2100

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 1850-01-01'

**branch_method**
'Hybrid-restart from year 2015-01-01 of historical'

**other information**

**Comment by YanchunHe** [comment] 2019-12-10 02:18
Sync to NS9034K:

2051	2060	
2061	2070	
2071	2080	
2081	2090	
2091	2100

**Comment by YanchunHe** [comment] 2019-12-12 07:34
When the above-listed years are synced to nird, please run the cmorization by:
```bash
cd /projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370
./cmor_tmp.sh -m=NorESM2-LM -e=ssp370 v=v20191108 &>>logs/cmor.log.v20191108 &
```
@jgriesfeller

**Comment by jgriesfeller** [comment] 2019-12-12 08:18
The sync to NIRD of all years has been finished over night.
starting the cmorisation now on login2

**Comment by jgriesfeller** [comment] 2019-12-12 08:19
changed to login3 as that had less load

**Comment by jgriesfeller** [comment] 2019-12-12 08:22
The job did not start. 
The log says:
--------------------
EXPID: ssp370       
--------------------
                    
START CMOR...       
Sun Dec  8 15:27:50 CET 2019             
                    
CaseName: NSSP370frc2_f19_tn14_20191014
expid   : ssp370
version : v20191108
real    : 1
2015 2020
2021 2030
2031 2040
2041 2050
2051 2060
2061 2070
ERROR: option v=v20191108 not allowed.
*** EXITING THE SCRIPT

**Comment by YanchunHe** [comment] 2019-12-12 08:25
sorry,

should be:

./cmor_tmp.sh -m=NorESM2-LM -e=ssp370 -v=v20191108 &>>logs/cmor.log.v20191108 &

( -v=xx, not v=xxx)

**Comment by jgriesfeller** [comment] 2019-12-12 08:29
no problem.
It seems it's doing something, the log looks different :-)

**Comment by jgriesfeller** [comment] 2019-12-12 08:36
I just realise that I cannot apply labels to issues in this repo. Otherwise I would have added the started label ;-)

**Comment by YanchunHe** [comment] 2019-12-12 08:52
I've sent you invitation to manage the issues, you should approve it, then you can make changes of them.

**Comment by jgriesfeller** [comment] 2019-12-12 09:20
The cmorisation did not start:
START CMOR...       
Thu Dec 12 09:26:49 CET 2019             
                    
CaseName: NSSP370frc2_f19_tn14_20191014
expid   : ssp370
version : v20191108
real    : 1
project : NS9560K
2051 2060
2061 2070
2071 2080
2081 2090
2091 2100
         
CMOR DONE
Thu Dec 12 09:29:19 CET 2019  
~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
PrePARE QC CHECK... 
2770 files           
                    
ERROR in v20191108.QCreport, EXIT...

How can I tell what's the problem?

**Comment by YanchunHe** [comment] 2019-12-12 09:57
looking at the error log:
/projects/NS9560K/cmor/noresm2cmor/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2051-2060r1.err

 1 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  2 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  3 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  4 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  5 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  6 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  7 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s
  8 ./noresm2cmor3_mpi: error while loading shared libraries: libifport.so.5: cannot open shared object file: No s

probably you need
```
source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh -arch intel64 -platform linux
```

But I have update the script, so that it should load it by default.

please try to submit again!

Cheers,
Yanchun

**Comment by jgriesfeller** [comment] 2019-12-12 10:14
Hi Yanchun, 
indeed since I never program in a compiled language at NIRD this is definitively missing.
Sourced the file and trying again

**Comment by jgriesfeller** [comment] 2019-12-12 10:33
the next try also did not succeed:
(base) [jang@login-nird-3 ssp370]$ cat /projects/NS9560K/cmor/noresm2cmor/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2091-2100r1.err 
find: '/projects/NS9560K/noresm/cases/NSSP370frc2_f19_tn14_20191014': No such file or directory

In case I do not hear anythin from Yanchun anymore, I will just link the data on /tos-project1/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014 to /projects/NS9560K/noresm/cases/NSSP370frc2_f19_tn14_20191014 and try again

**Comment by YanchunHe** [comment] 2019-12-12 10:36
OK, sorry, I forget that these data are transferred to NS9034K, not NS9560K.
Please go ahead with the link. 
I will try to  correct this later on.

**Comment by jgriesfeller** [comment] 2019-12-12 10:54
No Problem Yanchun, 
The question is if I should just do the linking anyway so that we also know what is where.

**Comment by YanchunHe** [comment] 2019-12-12 10:56
OK, I think we should not link it. Because there will store the actual output there under ns9560K after new disk is installed. I will correct the namelist.

**Comment by YanchunHe** [comment] 2019-12-12 10:59
I have corrected.
1, create a new file sysNS9034K under /projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370/v20191108
2, set -p=NS9034K in cmor_tmp.sh

You can try to do this if you encounter similar errors.

**Comment by jgriesfeller** [comment] 2019-12-12 12:09
the linking did not work, but -p=NS9024K did not work either.

the log says:
ERROR: option -p=NS9034K not allowed.

**Comment by YanchunHe** [comment] 2019-12-12 12:23
sorry, I meant I have added -p=NS9034K in the cmor_tmp.sh, you don't need to set the paramter when you run it. just run:

./cmor_tmp.sh -m=NorESM2-LM -e=ssp370 -v=v20191108 &>>logs/cmor.log.v20191108 &

should hopefully work.

**Comment by jgriesfeller** [comment] 2019-12-12 12:27
I can see some jobs named noresm2cmor3_mp under my user name now. So guess it does work. :-)

**Comment by jgriesfeller** [comment] 2019-12-12 12:55
this seems to have died as well:
--------------------
EXPID: ssp370       
--------------------
                    
START CMOR...       
Thu Dec 12 13:25:23 CET 2019             
                    
CaseName: NSSP370frc2_f19_tn14_20191014
expid   : ssp370
version : v20191108
real    : 1
project : NS9034K
2051 2060

after that nothing and nothing in top. Checking the other logs...

**Comment by jgriesfeller** [comment] 2019-12-12 13:10
I am now confused. 
Where is the output supposed to be?

**Comment by jgriesfeller** [comment] 2019-12-12 13:41
looking at the files, some have been created by me, but does this mean the cmorisation has been finished properly?
(base) [jang@login-nird-3 ~]$ ll -t /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/ | head
total 1195196192
drwxrwsr-x 2 yanchun ns9034k      524288 Dec 12 13:27 ./
-rw-rw-r-- 1 jang    ns9034k       65249 Dec 12 13:27 sftlf_fx_NorESM2-LM_ssp370_r1i1p1f1_gn.nc
-rw-rw-r-- 1 jang    ns9034k       48202 Dec 12 13:26 areacella_fx_NorESM2-LM_ssp370_r1i1p1f1_gn.nc
-rw-rw-r-- 1 jang    ns9034k       82327 Dec 12 13:26 orog_fx_NorESM2-LM_ssp370_r1i1p1f1_gn.nc
-rw-rw-r-- 1 jang    ns9034k       51690 Dec 12 13:26 sftgif_fx_NorESM2-LM_ssp370_r1i1p1f1_gn.nc
drwxrwsr-x 3 yanchun ns9034k       32768 Dec 12 11:57 ../
-rw-rw-r-- 1 yanchun ns9034k     3905577 Dec  9 18:56 tas_Amon_NorESM2-LM_ssp370_r1i1p1f1_gn_206101-207012.nc
-rw-rw-r-- 1 yanchun ns9034k    34718364 Dec  9 18:55 ua_Emon_NorESM2-LM_ssp370_r1i1p1f1_gn_206101-207012.nc
-rw-rw-r-- 1 yanchun ns9034k     4294075 Dec  9 18:54 rlutcs_Amon_NorESM2-LM_ssp370_r1i1p1f1_gn_206101-207012.nc

Yanchun, can this be published?

The logs do not seem to contain some errors.

**Comment by jgriesfeller** [comment] 2019-12-12 14:39
Yanchun, if do not hear anything from you until tomorrow morning, I am going to ask Alok to publish. There's actually 1.2 TB in the target directory:
(base) [jang@login-nird-0 cases]$ du -h /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108
1.2T	/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108

Just to be sure: If that is done, I can safely remove the input data from NIRD, right?

**Comment by YanchunHe** [comment] 2019-12-12 14:49
No, this is far from finished.
```
yanchun@login-nird-1:/projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370
$ ./checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	9
yyyy1	yyyy2	nf
2015	2020	607
2021	2030	607
2031	2040	607
2041	2050	607
2051	2060	292
2061	2070	41
2071	2080	0
2081	2090	0
2091	2100	0
Total:		2770
```
Please wait, and I can only further check this in the weekend.

**Comment by jgriesfeller** [comment] 2019-12-13 11:41
I am running the cmorisation for the years 2081 to 2100
The first period did not finish due to an HDF error (on a local file):
(base) [jang@login-nird-1 ssp370]$ tail ${CMOR_ROOT}/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2081-2090r1.log 
  "license": "CMIP6 model data produced by NCC is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https:\/\/creativecommons.org\/licenses). Consult https:\/\/pcmdi.llnl.gov\/CMIP6\/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:\/\/\/pcmdi.llnl.gov\/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."
}
 plev19:    100000.000000000        92500.0000000000     
   85000.0000000000        70000.0000000000        60000.0000000000     
   50000.0000000000        40000.0000000000        30000.0000000000     
   25000.0000000000        20000.0000000000        15000.0000000000     
   10000.0000000000        7000.00000000000        5000.00000000000     
   3000.00000000000        2000.00000000000        1000.00000000000     
   500.000000000000        100.000000000000     
 NetCDF: HDF error

After that the runcmor call from cmor.sh dies and does not continue with more files. Unfortunately I did not find the input file name in /projects/NS9560K/cmor/noresm2cmor/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2081-2090r1.err to check if the input file is corrupt or if the root cause is something else.

**Comment by jgriesfeller** [comment] 2019-12-13 11:46
When I checked the other incomplete periods there's some other problems also showing up which point to errors in cmor table or the data:

`(base) [jang@login-nird-1 ssp370]$ tail ${CMOR_ROOT}/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2051-2060r1.log 
}
 Resolve input variable term f12vmr =
  f12vmr*   1.00000000000000     
 Variable f12vmr has too few dimensions
 unexpected first dimension of variable f12vmr:            1  versus idm=
         144
 unexpected second dimension of variable f12vmr:            1  versus jdm=
         144
 Resolve input variable term TGCLDIWP =
  TGCLDIWP*   1.00000000000000    `

**Comment by YanchunHe** [comment] 2019-12-13 15:50
> When I checked the other incomplete periods there's some other problems also showing up which point to errors in cmor table or the data:
> 
> `(base) [jang@login-nird-1 ssp370]$ tail ${CMOR_ROOT}/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2051-2060r1.log } Resolve input variable term f12vmr = f12vmr* 1.00000000000000 Variable f12vmr has too few dimensions unexpected first dimension of variable f12vmr: 1 versus idm= 144 unexpected second dimension of variable f12vmr: 1 versus jdm= 144 Resolve input variable term TGCLDIWP = TGCLDIWP* 1.00000000000000 `

This should just a warning by cmor library, we should have fix this in the code long time ago so that the output has the right dimension. so I think we can ignore this, this is not an error.

**Comment by YanchunHe** [comment] 2019-12-13 15:52
> I am running the cmorisation for the years 2081 to 2100
> The first period did not finish due to an HDF error (on a local file):
> `(base) [jang@login-nird-1 ssp370]$ tail ${CMOR_ROOT}/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2081-2090r1.log "license": "CMIP6 model data produced by NCC is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https:\/\/creativecommons.org\/licenses). Consult https:\/\/pcmdi.llnl.gov\/CMIP6\/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:\/\/\/pcmdi.llnl.gov\/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." } plev19: 100000.000000000 92500.0000000000 85000.0000000000 70000.0000000000 60000.0000000000 50000.0000000000 40000.0000000000 30000.0000000000 25000.0000000000 20000.0000000000 15000.0000000000 10000.0000000000 7000.00000000000 5000.00000000000 3000.00000000000 2000.00000000000 1000.00000000000 500.000000000000 100.000000000000 NetCDF: HDF error `
> After that the runcmor call from cmor.sh dies and does not continue with more files. Unfortunately I did not find the input file name in /projects/NS9560K/cmor/noresm2cmor/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2081-2090r1.err to check if the input file is corrupt or if the root cause is something else.

This `HDF error` should be able to happen even for files in local disk, but much rare than those on mounted disk.

Should try to resumit and see if it overpass.

**Comment by jgriesfeller** [comment] 2019-12-13 23:40
started the years 2061 to 2080 now.
Current output of checkcmor.sh:
```(base) [jang@login-nird-1 ssp370]$ ./checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	9
yyyy1	yyyy2	nf
2015	2020	607
2021	2030	607
2031	2040	607
2041	2050	607
2051	2060	292
2061	2070	52
2071	2080	0
2081	2090	15
2091	2100	607
Total:		3403
```

**Comment by jgriesfeller** [comment] 2019-12-14 14:57
current status (period 2071 to 2080 still running)
(base) [jang@login-nird-3 ssp370]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	9
yyyy1	yyyy2	nf
2015	2020	607
2021	2030	607
2031	2040	607
2041	2050	607
2051	2060	292
2061	2070	607
2071	2080	529
2081	2090	15
2091	2100	607
Total:		4487

Started the incomplete periods on login3.
Hopefully this goes through this time.

**Comment by YanchunHe** [comment] 2019-12-14 15:22
Sounds great! But I suggest that you do not use the 'set -x' option in the script, otherwise too much unnecessary information in the log file. For detailed information of cmorization itself, it is find under noresm2cmor/logs/$model/$expid/$version/year1-year2.log

**Comment by jgriesfeller** [comment] 2019-12-14 23:43
The set -x was my way to understand the script better. Otherwise remove the additional output with grep -v ++ ;-)

**Comment by jgriesfeller** [comment] 2019-12-15 14:38
cmorisation died at period 2081 2090.
Started it again on login1
The rest looks complete:
```(base) [jang@login-nird-1 ssp370]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	9
yyyy1	yyyy2	nf
2015	2020	607
2021	2030	607
2031	2040	607
2041	2050	607
2051	2060	607
2061	2070	607
2071	2080	607
2081	2090	16
2091	2100	607
Total:		4881
```

**Comment by jgriesfeller** [comment] 2019-12-15 15:14
cmorisation dies with HDF error again after no new files.
Started again, but if this does not succeed I have to check all input files since I don't know how to tell on which file the error occurred.

**Comment by jgriesfeller** [comment] 2019-12-15 16:04
Unfortunately I am stuck here right now:
```
(base) [jang@login-nird-1 ssp370]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	9
yyyy1	yyyy2	nf
2015	2020	607
2021	2030	607
2031	2040	607
2041	2050	607
2051	2060	607
2061	2070	607
2071	2080	607
2081	2090	16
2091	2100	607
Total:		4881
Unfinished files:
46M Dec 15 16:58 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/hur_Amon_NorESM2-LM_ssp370_r1i1p1f1_gn8tDWMs52065.nc
43K Dec 15 16:57 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/hurs_Amon_NorESM2-LM_ssp370_r1i1p1f1_gng0v79x52066.nc
46M Dec 15 16:58 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/hus_Amon_NorESM2-LM_ssp370_r1i1p1f1_gnQDXn0o52067.nc
43K Dec 15 16:57 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/huss_Amon_NorESM2-LM_ssp370_r1i1p1f1_gnsJHDiG52068.nc
34K Dec 15 16:57 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/n2oglobal_Amon_NorESM2-LM_ssp370_r1i1p1f1_gmX0o3TI52070.nc
20M Dec 15 16:58 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/o3_Amon_NorESM2-LM_ssp370_r1i1p1f1_gnsHGDOR52071.nc
440K Dec 15 16:58 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/pr_Amon_NorESM2-LM_ssp370_r1i1p1f1_gnNFYwNp52072.nc
41K Dec 15 16:58 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20191108/psl_Amon_NorESM2-LM_ssp370_r1i1p1f1_gng2WQN552069.nc
Remove unfinished files [Y/N] 
```
log file:
```(base) [jang@login-nird-1 ssp370]$ tail /projects/NS9560K/cmor/noresm2cmor/logs/CMIP6_NorESM2-LM/ssp370/v20191108/2081-2090r1.log
  "branch_method": "Hybrid-restart from year 2015-01-01 of historical",
  "branch_time_in_child": 0.0E+0,
  "branch_time_in_parent": 0.60225E+5,
  "parent_time_units": "days since 1850-01-01",
  "tracking_prefix": "hdl:21.14100",
  "output_path_template": "<activity_id><institution_id><source_id><experiment_id><_member_id><table><variable_id><grid_label><version>",
  "output_file_template": "<variable_id><table><source_id><experiment_id><_member_id><grid_label>",
  "license": "CMIP6 model data produced by NCC is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https:\/\/creativecommons.org\/licenses). Consult https:\/\/pcmdi.llnl.gov\/CMIP6\/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:\/\/\/pcmdi.llnl.gov\/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."
}
 NetCDF: HDF error
```
I tried 3 times now, no progress. If I don't hear anything from Yanchun, I will test all input files for that period if they can be read without an HDF error. If don't find anything there, Yanchun has to take over.

**Comment by YanchunHe** [comment] 2019-12-16 09:51
Hi Jan, I will try to run 2081-2090 myself. I will keep you updated.

**Comment by YanchunHe** [comment] 2019-12-22 14:55
The noresm2cmor crashes due to the HDF error during processing `ozone` in file `/projects/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc`

log file reads:
```
 read_tslice, fname: /projects/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc
 read_tslice, ivnm1,ivnm2: ozone,
 NetCDF: HDF error
```

This crash is reproducible by running:
```
cd /projects/NS9560K/cmor/noresm2cmor/bin
pnml=/projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370/v20191108

/noresm2cmor3_dev ${pnml}/sysNS9034K.nml ${pnml}/mod.nml ${pnml}/exp_2081-2090r1.nml ${pnml}/var3.nml  &
```

I tried to turning on more detailed error log from netcdf/HDF, but not successful (following some discussions in http://netcdf-group.1586084.n2.nabble.com/NetCDF-HDF-error-and-now-what-td6921602.html).

I don't find obvious error in the above mentioned file `/projects/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc`

**Comment by YanchunHe** [comment] 2020-01-17 13:13
Come back to this issue again!

There are indeed error for ozone in NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc and NSSP370frc2_f19_tn14_20191014.cam.h0.2086-11.nc

for example,
```
$ ncdump -v ozone /projects/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc

...
	float ozone(time, lev, lat, lon) ;
		ozone:mdims = 1 ;
		ozone:units = "mol/mol" ;
		ozone:long_name = "prescribed ozone" ;

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.8.19" ;
		:Conventions = "CF-1.0" ;
		:source = "CAM" ;
		:case = "NSSP370frc2_f19_tn14_20191014" ;
		:logname = "olivie" ;
		:host = "" ;
		:initial_file = "NHIST_f19_tn14_20190710.cam.i.2015-01-01-00000.nc" ;
		:topography_file = "/cluster/shared/noresm/inputdata/atm/cam/topo/fv_1.9x2.5_nc3000_Nsw084_Nrs016_Co120_Fi001_ZR_061116.nc" ;
		:model_doi_url = "https://doi.org/10.5065/D67H1H0V" ;
		:time_period_freq = "month_1" ;
data:

 ozone =
NetCDF: HDF error
Location: file ../../ncdump/vardata.c; line 473
```

That is why, cmorization for year 2081-2091 always fails.

@DirkOlivie  Could you check this and find if there is possibility to fix this? e.g., rerun the simulation, or I can skip `ozone`.

**Comment by DirkOlivie** [comment] 2020-01-17 13:33
@YanchunHe 

I checked the file being on nird (ncdump -v ozone /projects/NS9034K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.m.h0.2086-10.nc), and I obtain the same error message as you.

However, when I check the file being on fram (ncdump -v ozone /cluster/NS9560K/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc) then I have no issue.

I should also try "being on fram but the file on nird", but on nird the directory "/projects/NS9560K/FRAM" is currently empty.

I will rerun the 2085-2089 period now and transfer the newly calculated cam.h0 files to the archive.  There is a possibility that the simulation might start during the weekend.

**Comment by YanchunHe** [comment] 2020-01-17 13:40
You can change to other login nodes, e.g, login3 currently, then /projects/NS9560K/FRAM is mounted (sometimes, it is not mounted on every login node).

I checked on nird, that:
ncdump -v ozone /projects/NS9560K/FRAM/noresm/cases/NSSP370frc2_f19_tn14_20191014/atm/hist/NSSP370frc2_f19_tn14_20191014.cam.h0.2086-10.nc
looks normal.

therefore, it is likely, this error is due to the stage of data transfer from fram to nird.

Since only these two files are wrong so far as I can see. I will try directly cmorize ozone from data on FRAM.

So you don't need to run the simulation now. I will let you know if need so in the future.

Thank you!

**Comment by jgriesfeller** [comment] 2020-01-17 14:07
The file in question is not noted in the transfer log for some reason. Very strange.
I just started the transfer once more. Should not take too long since the data is in nird mostly already.

**Comment by jgriesfeller** [comment] 2020-01-17 14:21
I had to delete and retransfer the file before it was actually readable on NIRD.

This basically means that the original file was somehow altered during the transfer. This never happened to me before. Even the file length was correct.

Anyway, there's a firs for everything.

Should be fine now.

**Comment by YanchunHe** [comment] 2020-01-24 06:43
finally get cmorized and ready to publish

**data path**
- /tos-project1/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108

**Comment by monsieuralok** [comment] 2020-01-30 13:38
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment] 2020-02-29 16:35
cmorized new data version to fix bugs reported in issues: #109 #178 #179 

**data path**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370/
- .r1i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment] 2020-03-02 11:06
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-02-12 09:11
Fail to cmorize with additional iLAMB variables (#262), AERday zg500 (#263) and corrected fNup (#251), with version v20210203. Unclear reason.

As this may not be critical for these experiments, I leave as it is and close the issue.

**Comment by YanchunHe** [comment] 2021-02-12 12:39
Found and corrected an small issue with setting to "activity_id" and the problem is resolved.

The above-mentioned fields are therefore cmorized and can be published.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp245
- .r3i1p1f1.sha256sum_v20210203
- .r2i1p1f1.sha256sum_v20210203
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment] 2021-02-16 20:28
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-04-12 10:16
New dataset version to fix issues #269, #270, #271, #272, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment] 2021-04-27 19:02
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-05-14 09:25
Data of the first month, 201501 is missing, see issue #277 
Could you retract all Emon, Lmon and LImon datasets of this ssp370? @monsieuralok 

I have recmorized these data, and can be republished to ESGF after retraction.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370

**data version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370
- .r1i1p1f1.sha256sum_v20210319b

**Comment by monsieuralok** [comment] 2021-05-28 12:43
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-08-30 13:08
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370/v20210818
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370

**version**
- v20210818

**sha256sum**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp370
- .r1i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment] 2021-09-01 09:38
@YanchunHe published

**Comment by monsieuralok** [comment] 2023-01-24 11:12
@YanchunHe retracted

**Closed by monsieuralok** 2023-01-24 11:12 UTC
Labels: Retract
