### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM - ssp126

### ISSUE THREAD

**Issue by matsbn** [NorESMhub/noresm2cmor#152] opened 2019-11-26 10:20 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/FRAM/noresm/cases

**experiment_id**
ssp126

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NSSP126frc2_f09_tn14_20191105, 2015-2100

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 1850-01-01' atm/lnd
'days since 0001-01-01' ice
'days since 1800-01-01' ocn

**branch_method**
'Hybrid-restart from year 2015-01-01 of historical'

**other information**

**Comment by jgriesfeller** [comment] 2019-12-12 15:02
Started transfer to NIRD at 
/tos-project1/NS9034K/noresm/cases/NSSP126frc2_f09_tn14_20191105

**Comment by jgriesfeller** [comment] 2019-12-13 08:56
Transfer has been completed over night. So the transfer from FRAM to NIRD is the way to go.
Since Yanchun seems to be occupied today, I will try to work out the cmorisation scripts myself, but no guarantees about the results...

**Comment by jgriesfeller** [comment] 2019-12-16 10:35
current status is this (run via the NFS link to FRAM):
```
(base) [jang@login-nird-1 ssp126]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	8
yyyy1	yyyy2	nf
2015	2020	103
2021	2030	581
2031	2040	191
2041	2050	0
2051	2060	139
2061	2070	133
2071	2080	102
2081	2090	153
2091	2100	567
Total:		1977
```
Since there's no two periods with the same number of files, I am just running the whole thing from NS9034K again. Host is login1

**Comment by YanchunHe** [comment] 2019-12-16 10:55
2021-2030 is complete, it is better if you can skip this.

You can simply kill your `cmor_NS9034K.sh` (don't kill all other noresm2cmor3_mpi programs).

And then edit the cmor_NS9034K.sh (skip 2021-2030), and finally submit it again.

**Comment by jgriesfeller** [comment] 2019-12-16 12:55
done

**Comment by jgriesfeller** [comment] 2019-12-17 07:59
current status (still running):
```
(base) [jang@login-nird-1 ssp126]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	8
yyyy1	yyyy2	nf
2015	2020	234
2021	2030	581
2031	2040	191
2041	2050	0
2051	2060	581
2061	2070	163
2071	2080	102
2081	2090	153
2091	2100	567
Total:		2580
```
This basically means that only one period finished since yesterday, even with local files... I don't think the NFS link is the root cause of the problem we see.

**Comment by jgriesfeller** [comment] 2019-12-18 07:34
current status (job has died again):
```
(base) [jang@login-nird-0 ssp126]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	8
yyyy1	yyyy2	nf
2015	2020	234
2021	2030	581
2031	2040	191
2041	2050	0
2051	2060	581
2061	2070	581
2071	2080	102
2081	2090	153
2091	2100	567
Total:		2998
Unfinished files:
```
again one more period than when I started the job yesterday. Again, I don't see an end of this with the current cmorisation system.

**Comment by YanchunHe** [comment] 2019-12-24 15:48
restarted..

**Comment by YanchunHe** [comment] 2019-12-28 04:25
cmorized and ready to publish to ESGF

**data path**
- /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126/v20191108
- /tos-project1/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126/r1i1p1f1

**version**
- v20191108

*sha256sum**
- /tos-project1/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126/.r1i1p1f1.sha256sum_v20191108

---
status:
$ ./checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	8
yyyy1	yyyy2	nf
2015	2020	581
2021	2030	581
2031	2040	581
2041	2050	581
2051	2060	581
2061	2070	581
2071	2080	581
2081	2090	581
2091	2100	581
Total:		5237

**Comment by YanchunHe** [comment] 2019-12-29 15:28
will remove synchronized model output under NS9034K.

**Comment by monsieuralok** [comment] 2019-12-30 09:00
@matsbn @YanchunHe published

**Comment by YanchunHe** [comment] 2020-02-27 12:03
cmorized new data version to fix bugs reported in issues: #109 #178 #179 

**data path**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126/
- .r1i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment] 2020-04-03 09:08
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-02-15 10:59
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126

**version**
- v20210203

**sha256sum**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment] 2021-03-03 11:13
@YanchunHe published

**Comment by YanchunHe** [comment] 2021-04-13 10:28
New dataset version to fix issues #269, #270, #271, #272, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment] 2021-04-29 12:29
@YanchunHe published

**Comment by monsieuralok** [comment] 2021-09-01 09:43
@YanchunHe published

**Comment by DirkOlivie** [comment] 2021-11-23 15:28
@YanchunHe I have rerun the SSP126 simulation with NorESM2-MM. The aim of the run was (1) to have extra high-frequency fields to force FLEXPART (these should not be cmorized), and (2) to have extra monthly aerosol diagnostics (hopefully these can be cmorized).

The new simulation is called NSSP126frc2_f09_tn14_20210825 and is on NS2345K in the directory :
 /projects/NS2345K/noresm/olivie/flexpart/NSSP126frc2_f09_tn14_20210825. 
The results of this simulation are bit-identical to the original simulation (NSSP126frc2_f09_tn14_20191105). I have checked that.

We are mainly interested in the cmorization of missing AERmon fields. Is it possible to run the cmorization for AERmon?

It is probably not a good idea to run the cmorization for all model components and all frequencies again. This new simulation contains for the atmosphere only the high-frequency fields needed for FLEXPART, and not the standard CMIP6 high frequency output (I think the cmorization would run into problems treating the high-frequency fields).  Also, I have transferred to nird only atm/hist  but not lnd/hist, ocn/hist, ice/hist, or rof/hist (those data would have been identical to the original simulation).

(long ago I have made a similar request for NorESM2-MM - ssp585; see issue #151)

I hope this is possible.
Dirk

**Comment by YanchunHe** [comment] 2021-11-30 21:33
Hi @DirkOlivie ,

The following variables `<variable>_AERmon_NorESM2-MM_ssp126_r1i1p1f1_gn_*.nc` are cmorized. Are they what you are expecting? If so, we can proceed with publish. (Not sure if @monsieuralok has come back to work).

```
abs550aer
airmass
chepsoa
drybc
drydust
dryoa
dryso4
dryss
mmraerh2o
mmrpm1
mmrpm2p5
od440aer
od550aer
od550aerh2o
od550bc
od550csaer
od550dust
od550lt1aer
od550oa
od550so4
od550ss
od870aer
wetbc
wetdust
wetoa
wetso4
wetss
```

**Comment by DirkOlivie** [comment] 2021-12-01 16:54
@YanchunHe, @monsieuralok, yes this looks fine. 
Thanks !

**Comment by YanchunHe** [comment] 2021-12-02 09:56
cmorized additional AERmon fields, and can be published to ESGF. @monsieuralok 

**data path**
* /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126/v20210908
* /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126

**version**
* v20210908

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126
* .r1i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment] 2021-12-13 10:29
@YanchunHe @DirkOlivie published

**Comment by monsieuralok** [comment] 2023-01-24 11:15
@YanchunHe retracted

**Comment by YanchunHe** [comment] 2023-06-30 12:28
cmorized 3-hourly preciptation data, and can be published to ESGF.

## data path

* /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp126/v20230616
* /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126

## version
* v20230616

## sha256sum

/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp126
* .r1i1p1f1.sha256sum_v20230616

**Comment by monsieuralok** [comment] 2023-08-29 12:10
@YanchunHe published

**Closed by monsieuralok** 2023-08-29 12:10 UTC
Labels: ESGF publish
