### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - pa-pdSIC, r1i1p1f1 - r35i1p1f1

### ISSUE THREAD

**Issue by JensBDebernard** [NorESMhub/noresm2cmor#238] opened 2020-09-14 08:28 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
- Members 1-35
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01000
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01001
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01002
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01003
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01004
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01005
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01006
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01007
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01008
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01009
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01010
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01011
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01012
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01013
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01014
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01015
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01016
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01017
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01018
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01019
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01020
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01021
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01022
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01023
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01024
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01025
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01026
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01027
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01028
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01029
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01030
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01031
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01032
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01033
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01034

- Full path to post-processed fields epfy, epfz, utendepfd, vtem, wtem (Eliassen-Palm fluxes and friends):
- Members 1-35
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01000
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01001
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01002
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01003
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01004
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01005
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01006
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01007
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01008
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01009
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01010
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01011
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01012
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01013
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01014
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01015
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01016
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01017
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01018
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01019
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01020
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01021
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01022
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01023
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01024
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01025
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01026
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01027
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01028
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01029
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01030
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01031
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01032
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01033
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01034

**experiment_id**
pa-pdSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NHIST_f19_tn14_pamip2p1_01000, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01001, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01002, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01003, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01004, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01005, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01006, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01007, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01008, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01009, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01010, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01011, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01012, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01013, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01014, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01015, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01016, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01017, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01018, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01019, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01020, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01021, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01022, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01023, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01024, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01025, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01026, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01027, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01028, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01029, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01030, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01031, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01032, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01033, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_01034, June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1

**parent_time_units**
'days since 1850-01-01'

**branch_method**
'Hybrid-restart from year 2000-04-01 of historic r1i1p1',

**other information**
Daily ice fields are collected together i daily files with the
structure casename.cice.h1.YYYY-MM.nc
Hybrid start from /projects/NS2345K/noresm/cases/NHIST_01_f19tn14_pamip-s_init which is a extension of the historical r1i1p1 from 2000-01-01 to 2000-04-01. Ice restart is aggregated to only one ice category.

**Comment by JensBDebernard** [comment] 2020-09-16 10:36
It would be very good if the cmorization of issues #238 -  #243 could be prioritized as they data has to be used in a project report with deadline in October this year. The data will go in to a multimodel analysis that rely on cmorized fields.

**Comment by YanchunHe** [comment] 2020-09-16 13:45
> It would be very good if the cmorization of issues #238 - #243 could be prioritized as they data has to be used in a project report with deadline in October this year. The data will go in to a multimodel analysis that rely on cmorized fields.

@JensBDebernard 
I am testing this and will soon start the cmorization.

**Comment by JensBDebernard** [comment] 2020-09-16 15:48
Greate! Thank you @YanchunHe !

**Comment by YanchunHe** [comment] 2020-09-18 07:11
There is error when reading files:
```
 NetCDF: Start+count exceeds dimension bound
```
Likely near the file `/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_01003/lnd/hist/NHIST_f19_tn14_pamip2p1_01003.clm2.h0.2000-06.nc`

I can only look into this at some point of the next week due to the coming workshop and meeting.

**Comment by lisesg** [comment] 2020-09-18 13:37
@YanchunHe if the problem is only with the files from CLM, than maybe one thought could be to initially just CMOR-ize the variables that have been requested for the project report, and then do the rest later. They have requested Amon variables siconc, psl, tas, pr, rsds, rsus, rlds, rlus, hfls, hfss, ua, wap, and zg. It this is a lot of extra work for you, then off course proceed as originally planned.

**Comment by YanchunHe** [comment] 2020-09-26 08:08
@lisesg 
I will cmorize only the Amon variables the next week if I can't spot where is the problem. Hopefully will finish all the experiments the next week.

**Comment by lisesg** [comment] 2020-09-26 08:35
@YanchunHe, that sounds good! Thanks! :)

**Comment by YanchunHe** [comment] 2020-09-28 12:16
OK, with some debug, I find the error arises when processing the part of sea ice (cice) output.

for example, for the variable `siitdconc`, derived from the model output `aicen`, has ice thickness categories, `Iceband` as one of its coordinate.

In the cmor tool, the iceband was hard-coded as iceband=5, which is true for, e.g. historical experiment.

But here, the `nc` coordinate of `aicen` is 1, therefore, the program crash with error for exceeding the dimension.

Wondering if there are standard/default number of iceband?  At least it is different here to the historical experiment.

If this is intended and may occur in the future, I can adjust the tool to adapt to the real number of `iceband` in the model output.

I will hopefully start the cmorization soon after your reply.

**Comment by JensBDebernard** [comment] 2020-09-28 20:46
Hi Yanchun,
Yes, that was also a difference ...
It is right that in the short pamip experiments, the number of ice
categories should be one (ncat=1).
In principle, ncat is free of choice, so we can imagine that someone wants
to change this but I think that is very unlikely with this version of the
model.

I also think the AMIP experiments are using ncat=1, so this was a little
surprising.

Best,
Jens

**Comment by YanchunHe** [comment] 2020-09-29 09:37
Thanks @JensBDebernard !

I updated the tool so that it can adapt to the ncat.

Here is an example of cmorized files, could you have a look and see if they seems OK?
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC/r1i1p1f1

There are minor issues of the coordinate of the EPflux files. They can be circumvented, but I will try to resolve it first.

**Comment by YanchunHe** [comment] 2020-10-01 12:38
Hi @lisesg 
As I mentioned above, the 'lev' variable/coordinate is missing in the pos-processed EP-flux files. As 'PS' is available in the file,  the cmor tool is looking for the 'lev' when loop through other variables in other "Tables" (not during EmonZ). And the program will crash at I don't find a smart way to skip this.

So could you add the 'lev' to your processed EP-flux files?

As the 'lev' should be the same for all the files, you can simply append it using NCO, e.g., 'ncks -v lev full_cam_output.nc epflux.nc'. (Or I can do this for you if you would like to).

Thanks!

Yanchun

**Comment by lisesg** [comment] 2020-10-01 13:29
@YanchunHe, no problem, I will add lev to the files straight away.

**Comment by lisesg** [comment] 2020-10-01 13:57
@YanchunHe, I've processed the files for the files used in this issue (memebers 1-35), so you can start testing if it works better now. I will process the files used in issues #239-#245 next.

**Comment by YanchunHe** [comment] 2020-10-01 14:20
Thanks! I tested, and it works well.

I will proceed with all other simulations.

**Comment by lisesg** [comment] 2020-10-01 15:09
Excellent, thanks! :)

**Comment by YanchunHe** [comment] 2020-10-02 09:22
cmorized and be ready to publish to ESGF

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-pdSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- .r1i1p1f1.sha256sum_v20200702
...
- .r105i1p1f1.sha256sum_v20200702

(realisation 1 to 105)

**Comment by JensBDebernard** [comment] 2020-10-05 09:09
Thanks Yanchun, 
Very good that you managed to get this through!

**Comment by lisesg** [comment] 2020-10-16 11:09
Hi @YanchunHe, sorry to ask for more data, but would it be possible to cmor-ize zg500 for issues #238-#245? Also, there does not appear to be any Omon variables for issues #238-#243 (pa-pdSIC and pa-futArcSIC); we had a request for tos, but I could not find it.

**Comment by monsieuralok** [comment] 2020-10-16 11:23
@lisesg @JensBDebernard @YanchunHe published

**Comment by YanchunHe** [comment] 2020-10-16 12:34
> Hi @YanchunHe, sorry to ask for more data, but would it be possible to cmor-ize zg500 for issues #238-#245? Also, there does not appear to be any Omon variables for issues #238-#243 (pa-pdSIC and pa-futArcSIC); we had a request for tos, but I could not find it.

Hi Lise,

Regarding to zg500, we are only able to cmorize zg500 in daily/6hourly data, is it available in the model output (Z500)?

For Omon variable, I think that is because I find the experiments are the first time done with "BLOM". I realised it late, and the upgrade the noresm2cmor tool to support this, after cmorized these issues. So experiments for pa-pdSIC-ext and pa-futArcSIC have Omon variables.
I will have to redo do cmorization to get Omon variables.

Yanchun

**Comment by lisesg** [comment] 2020-10-16 12:53
> Hi Lise,
> 
> Regarding to zg500, we are only able to cmorize zg500 in daily/6hourly data, is it available in the model output (Z500)?
> 
> For Omon variable, I think that is because I find the experiments are the first time done with "BLOM". I realised it late, and the upgrade the noresm2cmor tool to support this, after cmorized these issues. So experiments for pa-pdSIC-ext and pa-futArcSIC have Omon variables.
> I will have to redo do cmorization to get Omon variables.
> 
> Yanchun

Daily Z500 is available in the h1 files. It would be great if daily Z500 could be cmor-ized in in addition to the Omon variables, it's a very popular field. :)

**Comment by YanchunHe** [comment] 2020-10-16 19:56
I will redo for the Omon. But sound strange that Z500 is not cmorized, if it is already available in the daily output. But I will check that.

**Comment by YanchunHe** [comment] 2020-10-28 14:35
> I will redo for the Omon. But sound strange that Z500 is not cmorized, if it is already available in the daily output. But I will check that.

Found a small typo bug in the `var_CMIP6_NorESM2-LM.nml`, fixed in commit 09beb6cac27b9ca155e405a8e26472f1c625a50e, and Z500 will be cmorized.

**Comment by lisesg** [comment] 2020-10-28 14:38
> Found a small typo bug in the `var_CMIP6_NorESM2-LM.nml`, fixed in commit 09beb6cac27b9ca155e405a8e26472f1c625a50e, and Z500 will be cmorized.

Sounds good! Thanks for looking into this and fixing it Yanchun! :)

**Comment by YanchunHe** [comment] 2020-10-28 14:39
cmorized Z500 and with Omon, Ofx, Oyr and Emon, Eyr
Ready to be published to ESGF.

** data path **
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-pdSIC

**version**
- v20201001

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- .r1i1p1f1.sha256sum_v20201001
...
- .r35i1p1f1.sha256sum_v20201001


@monsieuralok Could you please publish this again? sorry for doing this twice!

**Comment by YanchunHe** [comment] 2020-10-30 10:00
(for my own note, no action are needed by others; please just ignore this update.)
Because of Emon has variables in different components, redo the cmorization of Emon for ocean output also introduce duplicated files from other components.
the duplicated cmorized files of v20201001 wrt v20200702 in Emon are removed.

**Comment by monsieuralok** [comment] 2020-11-29 14:30
@YanchunHe @JensBDebernard published

**Closed by monsieuralok** 2020-11-29 14:30 UTC
Labels: ESGF publish
