### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - ssp126-ssp370Lu

### ISSUE THREAD

**Issue by lca041** [NorESMhub/noresm2cmor#214] opened 2020-07-04 12:18 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/projects/NS9560K/noresm/cases/b.e21.NSSP126frc2.f19_tn14.CMIP6-SSP1-2.6-SSP3-7.0Lu.001

**experiment_id**
ssp126-ssp370Lu

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
b.e21.NSSP126frc2.f19_tn14.CMIP6-SSP1-2.6-SSP3-7.0Lu.001, 2015-2100

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**other information**
(provide other information that might be useful)
The sub-grid variables have already extracted and stored in the manner you requested.

**Comment by YanchunHe** [comment] 2020-07-14 13:02
cmorized and ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp126-ssp370Lu
- /projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/ssp126-ssp370Lu

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/ssp126-ssp370Lu
- .r1i1p1f1.sha256sum_v20200702

commit: 52c7d63

**Comment by monsieuralok** [comment] 2020-07-23 10:51
do not have write permission in : /projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/ssp126-ssp370Lu

**Comment by YanchunHe** [comment] 2020-07-27 09:18
write permission granted @monsieuralok

**Comment by monsieuralok** [comment] 2020-08-11 11:15
@YanchunHe @lca041 published

**Comment by DirkOlivie** [comment] 2024-04-11 13:25
I have plotted global timeseries of TREFHT, U10 and PS for the ssp126-ssp370LU simulation (comparing with historical and other SSP simulations).   ssp126-ssp370LU behaves very differently, so I assume it has not been correctly setup or initialized.  Does anyone  might know what went wrong in this model setup?  We could envision rerunning this simulation.  To make the plots, I used the raw data of experiment b.e21.NSSP126frc2.f19_tn14.CMIP6-SSP1-2.6-SSP3-7.0Lu.001.

Plots of TREFHT, U10 and PS :
![TREFHT_glob_YEA_n20240411_james_gomez](https://github.com/NorESMhub/noresm2cmor/assets/16320906/8cf535eb-0e37-4c21-a4fe-d3a931092e78)
![U10_glob_YEA_n20240411_james_gomez](https://github.com/NorESMhub/noresm2cmor/assets/16320906/2cf4b94b-c443-492a-b4fe-57a671b49698)
![PS_glob_YEA_n20240411_james_gomez](https://github.com/NorESMhub/noresm2cmor/assets/16320906/8d9643d1-2730-42c3-a6aa-fca4d5a5fdac)

Best regards,
Dirk

**Comment by oyvindseland** [comment] 2024-04-11 14:34
Hi

I found out from the ouput files and later confirmed from the log file that this model simulation use the topography file for NorESM2-MM, ie. the 1 degree version. So this simulation can not be used and must be retracted from ESGF.

**Comment by YanchunHe** [comment] 2024-04-12 08:16
> Hi
> 
> I found out from the ouput files and later confirmed from the log file that this model simulation use the topography file for NorESM2-MM, ie. the 1 degree version. So this simulation can not be used and must be retracted from ESGF.

OK.

Alok, could you please retract the whole experiment, and report the reason (as Øyvind described). Thanks!

@monsieuralok

**Comment by monsieuralok** [comment] 2024-04-30 10:54
@YanchunHe retracted and opened issue:- https://errata.ipsl.fr/static/view.html?uid=50576c46-c717-bd9c-a794-b5605da97d42

**Comment by YanchunHe** [comment] 2024-04-30 11:23
> @YanchunHe retracted and opened issue:- https://errata.ipsl.fr/static/view.html?uid=50576c46-c717-bd9c-a794-b5605da97d42

Thanks @monsieuralok !

However, as I can see, no one will redo these experiment, so they will not be republished in the future.

Great if you can revise the description, otherwise, it should be OK, and we close the issue here.

**Comment by monsieuralok** [comment] 2024-04-30 11:46
@YanchunHe revised the comment and closing it.

**Closed by monsieuralok** 2024-04-30 11:46 UTC
Labels: Retract
